apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-configmap
  namespace: multi-container-demo
data:
  initdb.sql: |
    CREATE TABLE Courses (id int(11) NOT NULL,  name varchar(255) DEFAULT NULL, code varchar(255) DEFAULT NULL, PRIMARY KEY (id));
    insert into Courses (id, name, code) values (1,'Systems Administration - III','RH294');
    insert into Courses (id, name, code) values (2,'Ansible Automation: Best Practices','DO447');
    insert into Courses (id, name, code) values (3,'OpenShift Administration - I','DO180');
    insert into Courses (id, name, code) values (4,'Openshift Administration - II','DO280');
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpass';
    ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'rootpass';
