apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: multi-container-demo
  labels:
    app: demo-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: demo-multi
  type: ClusterIP
